### PR TITLE
Fix duplicate paste

### LINKED ISSUE #1644: Pasting text from clipboard without formatting (via Ctrl+Shift+V) inserts text twice
**Bug description:**
When I try to paste text from clipboard without formatting (via Ctrl+Shift+V) on Ubuntu Linux, Ferdi inserts text twice, one after another. This happens with all services (GMail, Element, Slack, VK, etc).

In other Electron apps and Chromium browser this hotkey works well, without duplicating pasted text.

**Steps to reproduce:**

1. Copy to clipboard some formatted text, for example "One two three".
2. Paste it on any textfield inside Ferdi service, using "Ctrl+Shift+V" hotkey.
3. You will see the pasted text twice: `One two threeOne two three`

**Expected behavior**
Pasted text should appear one time.

**Environment:**

- Operating System: Ubuntu 20.04 with KDE 5.22
- Ferdi Version: 5.6.0-nightly.68

### PR DESCRIPTION
**Pull request by stnkl**
#### Pre-flight Checklist
- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Added `role`s to the paste and pasteAndMatchStyle menu items which prevents formatted text from being pasted twice. I tested this on Windows 20H2 only. 

~Also fixed an issue with wrongly displayed shortcuts in the application menu (it would show "CmdOrCtrl" instead of the platform specific "Cmd" or "Ctrl" for some menu items).~

#### Motivation and Context
This fixes #1644. 

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Fixed duplicate pasting of formatted text for Windows/Linux

### CODE REVIEW

File: src/lib/Menu.js [hunk 1]
```diff
@@ -629,7 +631,7 @@ const _titleBarTemplateFactory = (intl, locked) => [
       },
       {
         label: intl.formatMessage(menuItems.findInPage),
-        accelerator: 'CmdOrCtrl+F',
+        accelerator: `${ctrlKey}+F`,
```
Comment (vraravam) [inline src/lib/Menu.js:634]: Why is this change made? Why is this inconsistent with the other shortcuts in the same file? Please revert.

File: src/lib/Menu.js [hunk 2]
```diff
@@ -376,7 +376,7 @@ const _templateFactory = (intl, locked) => [
       },
       {
         label: intl.formatMessage(menuItems.openQuickSwitch),
-        accelerator: 'CmdOrCtrl+S',
+        accelerator: 'Cmd+S',
```
Comment (vraravam) [inline src/lib/Menu.js:379]: Why is this change made? Why is this inconsistent with the other shortcuts in the same file? Please revert.

**Review by vraravam — CHANGES_REQUESTED** [review]
Please revert all other changes, other than the `role`.

**Review by vraravam — CHANGES_REQUESTED** [review]

File: src/lib/Menu.js (hunk 1 above)
Comment (stnkl) [reply src/lib/Menu.js:634]: This change was made to fix this issue:

grafik

`CmdOrCtrl` does have the expected functional effect but as you can see doesn't change the label as it should (and I think it should according to the docs). There are other problems with the documentation. According to the docs adding a `role` should prevent the `click` event from firing which it doesn't. Adding the role `minimize` to the corresponding menu item doesn't have any effect. Instead we need to use the click event (as ferdi currently does) to actually minimize the window. However the documentation discourages from doing exactly that.

Actually this change increases consistency within `_templateFactory` (which is for macOS only) and `_titleBarTemplateFactory` (for Windows/linux) respectively but I understand that this is not related to the original issue so I will revert the changes.

Comment (vraravam) [reply src/lib/Menu.js:634]: or - you could use the `${cmdKey}` imported from `environment`?

File: src/lib/Menu.js (hunk 2 above)
Comment (vraravam) [reply src/lib/Menu.js:379]: you could use the `${cmdKey}` imported from `environment` here as well?

File: src/lib/Menu.js (hunk 1 above)
Comment (vraravam) [reply src/lib/Menu.js]: Yes - thanks - please create a new PR for the other issue that you are referring to.

Comment (stnkl) [reply src/lib/Menu.js]: I would suggest merging `_templateFactory` and `_titleBarTemplateFactory` to get rid of a lot of code duplication. I tried doing so but ran into too many problems where the behavior was different from what the documentation suggested so I gave up on that for now.

**Review by vraravam — APPROVED** [review]

**Comment by vraravam** [comment]
@all-contributors - please add @stnkl for code
