### PR TITLE
revert: partially revert fix for #1879 since the system tray doesn't quit the app if chosen

### LINKED ISSUE #1913: Unable to quit from system tray
**Bug description:**
I was unable to quit Ferdi using the system tray icon!

**Steps to reproduce:**

1. Start Ferdi
2. Enable the options "Keep Ferdi in the background" and "Show Ferdi on system tray"
3. Close the windows
4. Click on "Quit Ferdi" on system tray
5. The application remains working (the system tray remains and the applications is still running).

**Expected behavior**
The application is finished and the system tray disapear

**Environment:**

- Operating System: Windows 10 x64
- Ferdi Version: 5.6.1
- Server: ---

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉 https://github.com/sponsors/getferdi
  👉 https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
When trying to quit from the system tray, Ferdi would not quit.

#### Motivation and Context
fixes #1913 

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

File: src/lib/Tray.js [hunk 1]
```diff
@@ -176,22 +178,4 @@ export default class TrayIcon {
       __dirname, '..', 'assets', 'images', type, platform, `${asset}.${FILE_EXTENSION}`,
     ));
   }
-
-  // TODO: Extract this into a reusable component and remove the duplications
-  quitApp = () => {
-    const yesButtonIndex = 0;
-    let selection = yesButtonIndex;
-    if (window.ferdi.stores.settings.app.confirmOnQuit) {
```
Comment (mhatvan) [inline src/lib/Tray.js:184]: Looked at it locally. The terminal reports that ferdi errors with `window is not defined`, because we are in the main process. You would need to find a way to pass ferdi settings into Tray.

File: src/lib/Tray.js [hunk 2]
```diff
@@ -176,22 +178,4 @@ export default class TrayIcon {
...
-      selection = dialog.showMessageBoxSync(app.mainWindow, {
-        // TODO: Externalize strings
-        type: 'question',
-        message: 'Quit',
-        detail: 'Do you really want to quit Ferdi?',
-        buttons: ['Yes', 'No'],
-      });
-    }
-    if (selection === yesButtonIndex) {
```
Comment (mhatvan) [inline src/lib/Tray.js:193]: This if condition should move into the `confirmOnQuit` if clause.

Also, you need to add an else case for `confirmOnQuit` that does `app.quit()`, since otherwise the app would never quit for people without `confirmOnQuit` option set.

**Review by mhatvan — CHANGES_REQUESTED** [review]
We don't need to revert the feature. There are just a couple of code changes left to fix this properly.

File: src/lib/Tray.js (hunk 1 above)
Comment (vraravam) [reply src/lib/Tray.js:184]: yes - lets just revert the check for now and unblock the stable release. we can get it working correctly afterwards.

File: src/lib/Tray.js (hunk 2 above)
Comment (vraravam) [reply src/lib/Tray.js:193]: `confirmOnQuit` will either be `true` or `false`. The `false` bit is handled when `selection` is defaulted to the `yesButton` value up above. So, we dont need the `else` condition.

File: src/lib/Tray.js (hunk 1 above)
Comment (vraravam) [reply src/lib/Tray.js:184]: on more analysis: we are getting the app settings via the `ipcMain`  in line 53. We could possibly capture this setting value from there. Let me try

Comment (vraravam) [reply src/lib/Tray.js:184]: nope - that didn't work either

Comment (vraravam) [reply src/lib/Tray.js:184]: resolving and merging for the next nightly
