### PR TITLE
Expose Chrome version to todos webview (fix #1211)

### LINKED ISSUE #1211: TickTick not working (Ferdi ToDo's)
**Bug description:**
TickTick will not load. It sometimes will load after the initial setup (fresh install), but won't load at any point afterwards. This has been happening for months for me on multiple builds and computers, so figured I would make a ticket. Other To Do lists load fine

**Steps to reproduce:**

1. Go to File > Settings > General Tab
2. Change Todo Server to TickTick (or use the custom web addres)
3. TickTick gets stuck on a loading screen.

**Expected behavior**
TickTick should load. 

**Screenshots**
image

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6 - Nightly 15

- Server: Franz (I think)
- Debug information:

### PR DESCRIPTION
**Pull request by kris7t**
### Description
The TickTick todo service fails to load if the Chrome version number does not appear in the User-Agent string. However, login to Google Tasks is prevented by the same.

We adopt the "chromeless" User-Agent logic from the service webview, which selectively exposes the Chrome version everywhere except the Google login screen. The common logic was moved into the userAgent-helpers module.

### Motivation and Context
Fixes #1211 

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

File: src/features/todos/store.js [hunk 1]
```diff
@@ -123,9 +127,34 @@ export default class TodoStore extends FeatureStore {
...
     debug('_setTodosWebview', webview);
-    this.webview = webview;
+    if (this.webview !== webview) {
+      this.webview = webview;
+      this._listenWebviewEvents();
+    }
   };
 
+  _listenWebviewEvents() {
+    const handleUserAgent = (url, forwardingHack = false) => {
```
Comment (vraravam) [inline src/features/todos/store.js:137]: @kris7t - isn't this `handleUserAgent` function duplicated between here and the `Service` model? If so, can the duplication be removed?

**Review by vraravam — CHANGES_REQUESTED** [review]

File: src/features/todos/store.js (hunk 1 above)
Comment (kris7t) [reply src/features/todos/store.js:137]: It is not an exact duplicate, because in the `Service` model, the "chromeful" user agent is `this.userAgent`, i.e., whatever the recipe specifies for the service. Nevertheless, I was thinking about how to extract the common logic into a new model (holding the "chromeful" user agent and the corresponding flag as state) that is used by composition in both `Service` and here. I can try to do that, but I don't know off the top of my had how to do that with mobx models.

Comment (vraravam) [reply src/features/todos/store.js:137]: ok - if it is much more convoluted, lets put a `TODO` in both places and move onto approving this PR. We can solve the `TODO` at a later date.

**Review by vraravam — APPROVED** [review]
I haven't run this on my local - but, it seems correct. Please merge based on your confidence and local testing.

**Comment by Rixxx-git** [comment]
Is this fix already part of the latest beta version? 🙂  I just installed the latest beta but ticktick is still stuck on loading. I don't know why but it worked the first time I set up the todo service. On restart it gets stuck on loading.

**Comment by kris7t** [comment]
@Rixxx-git No, but it should arrive in a nightly soon.

**Comment by Rixxx-git** [comment]
Alright. Thank you for your help!

**Comment by Rixxx-git** [comment]
@kris7t Will this issue be fixed in the upcoming version 5.6.0?

**Comment by kris7t** [comment]
This should already be in the latest beta, I think.

**Comment by vraravam** [comment]
I just released v5.6.0 - this should be in there!
The website and homebrew formulae are still in the process of being approved/merged. Please see progress in #1017
