### PR TITLE
Change Keyboard shortcut tooltip text in Sidebar for Settings

### LINKED ISSUE #655: Keyboard shortcut for Settings not working in 5.5.0 in Windows 10
**Describe the bug**

The keyboard short for Settings screen `Ctrl+,` does not seem to be working.

**To Reproduce**

1. Open Ferdi
2. Press `Ctrl + ,`
3. Settings screen does not open

**Expected behavior**

Settings screen has to open on pressing `Ctrl + ,`

**Screenshots**

image

**Desktop:**

- OS: Windows 10
- Ferdi Version 5.5.0

- Server Used: https://api.getferdi.com

### PR DESCRIPTION
**Pull request by sampathBlam**
Change the Keyboard shortcut tooltip text in Sidebar for Settings to be platform-specific 

### Description

- Tooltip text was previously hardcoded as `Ctrl+,` irrespective of the platform
- Change it to `Ctrl+P` for Windows.
- Stick to `Cmd+,` for Mac

### Motivation and Context

Fixes #655 

### How Has This Been Tested?

Tested in Windows 10 Local dev environment.

### Screenshots (if appropriate):

Windows
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ npm run lint`).

### CODE REVIEW

**Comment by vantezzen** [comment]
Looks like we need to make this message platform-specific: The shortcut is actually "CMD+," on Mac.

**Comment by sampathBlam** [comment]
@vantezzen : Sure, will do it.

**Comment by sampathBlam** [comment]
@vantezzen : If the actual shortcut is `CMD+,` in mac, I can do the following things
- Change the short cut in windows to `Ctrl + ,` to make it uniform with Mac.
- Change the text message as platform specific.

Does that sound good?

**Comment by sampathBlam** [comment]
@vantezzen : I do not have a mac. Can you please provide a screenshot clip of how it looks like in the sidebar as well as the top menu bar? 
And which one works in Mac ? CMD+P or CMD+, ?

**Comment by sampathBlam** [comment]
@vantezzen : Can we stick to **P** instead of comma for settings shortcut, in all platforms? I feel alphabets are more explicit and user friendly than punctuations in case of shortcuts. We can use Ctrl or Cmd based on platform.

**Comment by vantezzen** [comment]
> Can we stick to P instead of comma for settings shortcut, in all platforms

"CMD + ," is the universal shortcut for settings on mac - it is used by pretty much every application so I think we should also stick to that.

**Comment by sampathBlam** [comment]
Sure. Thanks for the clarification. If that is the case, can we change it to `Ctrl + ,` for windows as well ?

File: src/components/layout/Sidebar.js [hunk 1]
```diff
@@ -189,12 +189,13 @@ export default @inject('stores', 'actions') @observer class Sidebar extends Comp
...
           onClick={() => openSettings({ path: 'app' })}
           className="sidebar__button sidebar__button--settings"
-          data-tip={`${intl.formatMessage(messages.settings)} (${ctrlKey}+,)`}
+          data-tip={`${intl.formatMessage(messages.settings)} (${ctrlKey}+P)`}
         >
           <i className="mdi mdi-settings" />
           { (this.props.stores.app.updateStatus === this.props.stores.app.updateStatusTypes.AVAILABLE
             || this.props.stores.app.updateStatus === this.props.stores.app.updateStatusTypes.DOWNLOADED) && (
             <span className="update-available">
+
```
Comment (kytwb) [inline src/components/layout/Sidebar.js:198]: Please remove this new extra line 🙏 It may have an impact on the rendering of the `update-available` indicator.

Comment (kytwb) [reply src/components/layout/Sidebar.js:198]:
```suggestion
```

**Comment by kytwb** [comment]
@sampathBlam I don't think we should change the shortcut; we had regressions on shortcuts in the past and users came to report about it even if we did not notice / were not using them ourselves in the review. So one of the lessons learned from this was to not change the defaults if possible. 
Do you think we could conditionally display the appropriate shortcut based on the platform the same way it is done for the menu?

**Comment by sampathBlam** [comment]
@kytwb : Made the necessary changes. I have updated the PR description accordingly. Please check if it is fine.

File: src/components/layout/Sidebar.js [hunk 2]
```diff
@@ -6,11 +6,14 @@ import { inject, observer } from 'mobx-react';
...
 
 import Tabbar from '../services/tabs/Tabbar';
-import { ctrlKey } from '../../environment';
+import { ctrlKey, isMac } from '../../environment';
 import { workspaceStore } from '../../features/workspaces';
 import { todosStore } from '../../features/todos';
 import { todoActions } from '../../features/todos/actions';
 
+// Platform specific shortcut keys
+export const settingsShortcutKey = isMac ? ',' : 'P';
```
Comment (kytwb) [inline src/components/layout/Sidebar.js:15]: I am not sure why we export it here, was it to be re-used somewhere?

Comment (sampathBlam) [reply src/components/layout/Sidebar.js:15]: My bad. that is silly. Initially thought of having it in the environment.js file. And forgot to remove the export part. I will do it now.

Comment (sampathBlam) [reply src/components/layout/Sidebar.js]: @kytwb Removed the unwanted export and updated the PR. Please check. Thanks.
